AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - tmp/**
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/**
  TargetRubyVersion: 2.6

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

Layout/LineLength:
  Exclude:
    - 'config/**/*'

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
