# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

if Album.count.zero?
  album_01 = Album.create(name: 'High Voltage', cover_image: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Acdc_high_voltage_international_album.jpg', year: 1976)
  Song.create(album: album_01, name: "It's a Long Way to the Top (If You Wanna Rock 'n' Roll)", duration: '5:01')
  Song.create(album: album_01, name: "Rock 'n' Roll Singer", duration: '5:04')
  Song.create(album: album_01, name: "The Jack", duration: '5:52')
  Song.create(album: album_01, name: "Live Wire", duration: '5:49')
  Song.create(album: album_01, name: "T.N.T.", duration: '3:35')
  Song.create(album: album_01, name: "Can I Sit Next to You Girl", duration: '4:11')
  Song.create(album: album_01, name: "Little Lover", duration: '5:38')
  Song.create(album: album_01, name: "She's Got Balls", duration: '4:51')
  Song.create(album: album_01, name: "High Voltage", duration: '4:14')

  album_02 = Album.create(name: 'Dirty Deeds Done Dirt Cheap', cover_image: 'https://upload.wikimedia.org/wikipedia/en/5/51/Dirty_Deeds_Done_Dirt_Cheap_%28ACDC_album_-_cover_art0.jpg', year: 1976)
  Song.create(album: album_02, name: "Dirty Deeds Done Dirt Cheap", duration: '3:52')
  Song.create(album: album_02, name: "Love at First Feel", duration: '3:11')
  Song.create(album: album_02, name: "Big Balls", duration: '2:39')
  Song.create(album: album_02, name: "Rocker", duration: '2:51')
  Song.create(album: album_02, name: "Problem Child", duration: '5:46')
  Song.create(album: album_02, name: "There's Gonna Be Some Rockin'", duration: '3:18')
  Song.create(album: album_02, name: "Ain't No Fun (Waiting 'Round to Be a Millionaire)", duration: '6:54')
  Song.create(album: album_02, name: "Ride On", duration: '5:50')
  Song.create(album: album_02, name: "Squealer", duration: '5:27')

  album_03 = Album.create(name: 'Let There Be Rock', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/ACDC-LetThereBeRock.jpg/220px-ACDC-LetThereBeRock.jpg', year: 1977)
  Song.create(album: album_03, name: "Go Down", duration: '5:31')
  Song.create(album: album_03, name: "Dog Eat Dog", duration: '3:35')
  Song.create(album: album_03, name: "Let There Be Rock", duration: '6:06')
  Song.create(album: album_03, name: "Bad Boy Boogie", duration: '4:28')
  Song.create(album: album_03, name: "Problem Child", duration: '5:25')
  Song.create(album: album_03, name: "Overdose", duration: '6:09')
  Song.create(album: album_03, name: "Hell Ain't a Bad Place to Be", duration: '4:14')
  Song.create(album: album_03, name: "Whole Lotta Rosie", duration: '5:34')

  album_04 = Album.create(name: 'Powerage', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/de/Acdc_Powerage.JPG/220px-Acdc_Powerage.JPG', year: 1978)
  Song.create(album: album_04, name: "Rock 'n' Roll Damnation", duration: '3:38')
  Song.create(album: album_04, name: "Down Payment Blues", duration: '6:04')
  Song.create(album: album_04, name: "Gimme a Bullet", duration: '3:22')
  Song.create(album: album_04, name: "Riff Raff", duration: '5:12')
  Song.create(album: album_04, name: "Sin City", duration: '4:45')
  Song.create(album: album_04, name: "What's Next to the Moon", duration: '3:32')
  Song.create(album: album_04, name: "Gone Shootin'", duration: '5:06')
  Song.create(album: album_04, name: "Up to My Neck in You", duration: '4:13')
  Song.create(album: album_04, name: "Kicked in the Teeth", duration: '4:03')

  album_05 = Album.create(name: 'Highway to Hell', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/ac/Acdc_Highway_to_Hell.JPG/220px-Acdc_Highway_to_Hell.JPG', year: 1979)
  Song.create(album: album_05, name: "Highway to Hell", duration: '3:28')
  Song.create(album: album_05, name: "Girls Got Rhythm", duration: '3:23')
  Song.create(album: album_05, name: "Walk All Over You", duration: '5:10')
  Song.create(album: album_05, name: "Touch Too Much", duration: '4:26')
  Song.create(album: album_05, name: "Beating Around the Bush", duration: '3:56')
  Song.create(album: album_05, name: "Shot Down in Flames", duration: '3:23')
  Song.create(album: album_05, name: "Get It Hot", duration: '2:35')
  Song.create(album: album_05, name: "If You Want Blood (You've Got It)", duration: '4:34')
  Song.create(album: album_05, name: "Love Hungry Man", duration: '4:17')
  Song.create(album: album_05, name: "Night Prowler", duration: '6:28')

  album_06 = Album.create(name: 'Back in Black', cover_image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/ACDC_Back_in_Black_cover.svg/220px-ACDC_Back_in_Black_cover.svg.png', year: 1980)
  Song.create(album: album_06, name: "Hells Bells", duration: '5:12')
  Song.create(album: album_06, name: "Shoot to Thrill", duration: '5:17')
  Song.create(album: album_06, name: "What Do You Do for Money Honey", duration: '3:36')
  Song.create(album: album_06, name: "Given the Dog a Bone", duration: '3:32')
  Song.create(album: album_06, name: "Let Me Put My Love into You", duration: '4:15')
  Song.create(album: album_06, name: "Back in Black", duration: '4:15')
  Song.create(album: album_06, name: "You Shook Me All Night Long", duration: '3:30')
  Song.create(album: album_06, name: "Have a Drink on Me", duration: '3:58')
  Song.create(album: album_06, name: "Shake a Leg", duration: '4:06')
  Song.create(album: album_06, name: "Rock and Roll Ain't Noise Pollution", duration: '4:26')

  album_07 = Album.create(name: 'For Those About to Rock We Salute You', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/ForThoseAboutToRock_ACDCalbum.jpg/220px-ForThoseAboutToRock_ACDCalbum.jpg', year: 1981)
  Song.create(album: album_07, name: "For Those About to Rock (We Salute You)", duration: '5:44')
  Song.create(album: album_07, name: "Put the Finger on You", duration: '3:26')
  Song.create(album: album_07, name: "Let's Get It Up", duration: '3:54')
  Song.create(album: album_07, name: "Inject the Venom", duration: '3:31')
  Song.create(album: album_07, name: "Snowballed", duration: '3:23')
  Song.create(album: album_07, name: "Evil Walks", duration: '4:24')
  Song.create(album: album_07, name: "C.O.D.", duration: '3:20')
  Song.create(album: album_07, name: "Breaking the Rules", duration: '4:23')
  Song.create(album: album_07, name: "Night of the Long Knives", duration: '3:26')
  Song.create(album: album_07, name: "Spellbound", duration: '4:39')

  album_08 = Album.create(name: 'Flick of the Switch', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Ac-dc_Flick_of_the_Switch.JPG/220px-Ac-dc_Flick_of_the_Switch.JPG', year: 1983)
  Song.create(album: album_08, name: "Rising Power", duration: '3:44')
  Song.create(album: album_08, name: "This House Is on Fire", duration: '3:23')
  Song.create(album: album_08, name: "Flick of the Switch", duration: '3:14')
  Song.create(album: album_08, name: "Nervous Shakedown", duration: '4:27')
  Song.create(album: album_08, name: "Landslide", duration: '3:58')
  Song.create(album: album_08, name: "Guns for Hire", duration: '3:25')
  Song.create(album: album_08, name: "Deep in the Hole", duration: '3:20')
  Song.create(album: album_08, name: "Bedlam in Belgium", duration: '3:52')
  Song.create(album: album_08, name: "Badlands", duration: '3:39')
  Song.create(album: album_08, name: "Brain Shake", duration: '4:09')

  album_09 = Album.create(name: "'74 Jailbreak", cover_image: 'https://upload.wikimedia.org/wikipedia/en/d/dd/Ac-dc-74-jailbreak-cover.jpg', year: 1983)
  Song.create(album: album_09, name: "Jailbreak", duration: '4:41')
  Song.create(album: album_09, name: "You Ain't Got A Hold On Me", duration: '3:31')
  Song.create(album: album_09, name: "Show Business", duration: '4:46')
  Song.create(album: album_09, name: "Souls Stripper", duration: '6:25')
  Song.create(album: album_09, name: "Baby Please Don't Go", duration: '5:00')

  album_10 = Album.create(name: 'Fly on the Wall', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/09/Fly_On_The_Wall.jpg/220px-Fly_On_The_Wall.jpg', year: 1985)
  Song.create(album: album_10, name: "Fly on the Wall", duration: '3:44')
  Song.create(album: album_10, name: "Shake Your Foundations", duration: '4:11')
  Song.create(album: album_10, name: "First Blood", duration: '3:46')
  Song.create(album: album_10, name: "Danger", duration: '4:22')
  Song.create(album: album_10, name: "Sink the Pink", duration: '4:15')
  Song.create(album: album_10, name: "Playing with Girls", duration: '3:45')
  Song.create(album: album_10, name: "Stand Up", duration: '3:53')
  Song.create(album: album_10, name: "Hell or High Water", duration: '4:32')
  Song.create(album: album_10, name: "Back in Business", duration: '4:24')
  Song.create(album: album_10, name: "Send for the Man", duration: '3:37')

  album_11 = Album.create(name: 'Who Made Who', cover_image: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Whomadewho.jpg', year: 1986)
  Song.create(album: album_11, name: "Who Made Who", duration: '3:27')
  Song.create(album: album_11, name: "You Shook Me All Night Long", duration: '3:31')
  Song.create(album: album_11, name: "D.T.", duration: '2:54')
  Song.create(album: album_11, name: "Sink the Pink", duration: '4:13')
  Song.create(album: album_11, name: "Ride On", duration: '5:50')
  Song.create(album: album_11, name: "Hells Bells", duration: '5:13')
  Song.create(album: album_11, name: "Shake Your Foundations", duration: '3:52')
  Song.create(album: album_11, name: "Chase the Ace", duration: '3:01')
  Song.create(album: album_11, name: "For Those About to Rock (We Salute You)", duration: '5:54')

  album_12 = Album.create(name: 'Blow Up Your Video', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Blowupyourvideo.jpg/220px-Blowupyourvideo.jpg', year: 1988)
  Song.create(album: album_12, name: "Heatseeker", duration: '3:50')
  Song.create(album: album_12, name: "That's the Way I Wanna Rock 'n' Roll", duration: '3:45')
  Song.create(album: album_12, name: "Meanstreak", duration: '4:08')
  Song.create(album: album_12, name: "Go Zone", duration: '4:26')
  Song.create(album: album_12, name: "Kissin' Dynamite", duration: '3:58')
  Song.create(album: album_12, name: "Nick of Time", duration: '4:16')
  Song.create(album: album_12, name: "Some Sin for Nuthin'", duration: '4:11')
  Song.create(album: album_12, name: "Ruff Stuff", duration: '4:29')
  Song.create(album: album_12, name: "Two's Up", duration: '5:20')
  Song.create(album: album_12, name: "This Means War", duration: '4:32')

  album_13 = Album.create(name: 'The Razors Edge', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a8/Razorsedge.jpg/220px-Razorsedge.jpg', year: 1990)
  Song.create(album: album_13, name: "Thunderstruck", duration: '4:53')
  Song.create(album: album_13, name: "Fire Your Guns", duration: '2:54')
  Song.create(album: album_13, name: "Moneytalks", duration: '3:46')
  Song.create(album: album_13, name: "The Razors Edge", duration: '4:23')
  Song.create(album: album_13, name: "Mistress for Christmas", duration: '4:00')
  Song.create(album: album_13, name: "Rock Your Heart Out", duration: '4:07')
  Song.create(album: album_13, name: "Are You Ready", duration: '4:10')
  Song.create(album: album_13, name: "Got You by the Balls", duration: '4:30')
  Song.create(album: album_13, name: "Shot of Love", duration: '3:57')
  Song.create(album: album_13, name: "Let's Make It", duration: '3:32')
  Song.create(album: album_13, name: "Goodbye & Good Riddance to Bad Luck", duration: '3:14')
  Song.create(album: album_13, name: "If You Dare", duration: '3:18')

  album_14 = Album.create(name: 'Ballbreaker', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Ballbreaker.jpg/220px-Ballbreaker.jpg', year: 1995)
  Song.create(album: album_14, name: "Hard as a Rock", duration: '4:31')
  Song.create(album: album_14, name: "Cover You in Oil", duration: '4:33')
  Song.create(album: album_14, name: "Ghe Furor", duration: '4:11')
  Song.create(album: album_14, name: "Boogie Man", duration: '4:07')
  Song.create(album: album_14, name: "The Honey Roll", duration: '5:35')
  Song.create(album: album_14, name: "Burnin' Alive", duration: '5:06')
  Song.create(album: album_14, name: "Hail Caesar", duration: '5:14')
  Song.create(album: album_14, name: "Love Bomb", duration: '3:14')
  Song.create(album: album_14, name: "Caught with Your Pants Down", duration: '4:15')
  Song.create(album: album_14, name: "Whiskey on the Rocks", duration: '4:35')
  Song.create(album: album_14, name: "Ballbreaker", duration: '4:31')

  album_15 = Album.create(name: 'Stiff Upper Lip', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/09/Stiff_Upper_Lip.jpg/220px-Stiff_Upper_Lip.jpg', year: 2000)
  Song.create(album: album_15, name: "Stiff Upper Lip", duration: '3:35')
  Song.create(album: album_15, name: "Meltdown", duration: '3:41')
  Song.create(album: album_15, name: "House of Jazz", duration: '3:56')
  Song.create(album: album_15, name: "Hold Me Back", duration: '3:59')
  Song.create(album: album_15, name: "Safe in New York City", duration: '3:59')
  Song.create(album: album_15, name: "Can't Stand Still", duration: '3:41')
  Song.create(album: album_15, name: "Can't Stop Rock 'n' Roll", duration: '4:02')
  Song.create(album: album_15, name: "Satellite Blues", duration: '3:46')
  Song.create(album: album_15, name: "Damned", duration: '3:52')
  Song.create(album: album_15, name: "Come and Get It", duration: '4:06')
  Song.create(album: album_15, name: "All Screwed Up", duration: '4:36')
  Song.create(album: album_15, name: "Give It Up", duration: '3:56')

  album_16 = Album.create(name: 'Black Ice', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3e/Black_ice_red.jpg/220px-Black_ice_red.jpg', year: 2008)
  Song.create(album: album_16, name: "Rock 'n' Roll Train", duration: '4:22')
  Song.create(album: album_16, name: "Skies on Fire", duration: '3:34')
  Song.create(album: album_16, name: "Big Jack", duration: '3:57')
  Song.create(album: album_16, name: "Anything Goes", duration: '3:22')
  Song.create(album: album_16, name: "War Machine", duration: '3:10')
  Song.create(album: album_16, name: "Smash 'n' Grab", duration: '4:06')
  Song.create(album: album_16, name: "Spoilin' for a Fight", duration: '3:17')
  Song.create(album: album_16, name: "Wheels", duration: '3:28')
  Song.create(album: album_16, name: "Decibel", duration: '3:34')
  Song.create(album: album_16, name: "Stormy May Day", duration: '3:10')
  Song.create(album: album_16, name: "She Likes Rock 'n' Roll", duration: '3:53')
  Song.create(album: album_16, name: "Money Made", duration: '4:15')
  Song.create(album: album_16, name: "Rock 'n' Roll Dream", duration: '4:41')
  Song.create(album: album_16, name: "Rocking All the Way", duration: '3:22')
  Song.create(album: album_16, name: "Black Ice", duration: '3:25')

  album_17 = Album.create(name: 'Rock or Bust', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7f/Rock_or_Bust.jpg/220px-Rock_or_Bust.jpg', year: 2014)
  Song.create(album: album_17, name: "Rock or Bust", duration: '3:03')
  Song.create(album: album_17, name: "Play Ball", duration: '2:47')
  Song.create(album: album_17, name: "Rock the Blues Away", duration: '3:24')
  Song.create(album: album_17, name: "Miss Adventure", duration: '2:57')
  Song.create(album: album_17, name: "Dogs of War", duration: '3:35')
  Song.create(album: album_17, name: "Got Some Rock & Roll Thunder", duration: '3:23')
  Song.create(album: album_17, name: "Hard Times", duration: '2:44')
  Song.create(album: album_17, name: "Baptism by Fire", duration: '3:30')
  Song.create(album: album_17, name: "Rock the House", duration: '2:43')
  Song.create(album: album_17, name: "Sweet Candy", duration: '3:10')
  Song.create(album: album_17, name: "Emission Control", duration: '3:41')

  album_18 = Album.create(name: 'Power Up', cover_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/ACDCPowerUp.jpg/220px-ACDCPowerUp.jpg', year: 2020)
  Song.create(album: album_18, name: "Realize", duration: '3:37')
  Song.create(album: album_18, name: "Rejection", duration: '4:06')
  Song.create(album: album_18, name: "Shot in the Dark", duration: '3:05')
  Song.create(album: album_18, name: "Through the Mists of Time", duration: '3:32')
  Song.create(album: album_18, name: "Kick You When You're Down", duration: '3:10')
  Song.create(album: album_18, name: "Witch's Spell", duration: '3:42')
  Song.create(album: album_18, name: "Demon Fire", duration: '3:30')
  Song.create(album: album_18, name: "Wild Reputation", duration: '2:54')
  Song.create(album: album_18, name: "No Man's Land", duration: '3:40')
  Song.create(album: album_18, name: "Systems Down", duration: '3:13')
  Song.create(album: album_18, name: "Money Shot", duration: '3:05')
  Song.create(album: album_18, name: "Code Red", duration: '3:31')
end
